#
#Sun May 24 22:46:17 CEST 2026
enable-bandage=true
enable-charcoal_block=true
enable-fuel_block=true
enable-knapsack=true
enable-medicated-bandage=true
enable-mercy-blade=true
enable-paint-filler=true
enable-salve=true
