# || =========== [SWPM Configs] =========== ||
[swpm]
	# || Remove the XP cost for renaming items.
	remove_renaming_xp_cost = true
	# || List of dimensions and their difficulties.
	# || If a dimension is not listed, it will choose difficulty from the default_difficulty config option.
	# || Difficulty names are used same as the /difficulty command
	# || Leave empty to disable dimensional difficulties.
	# || Format: modid:dimension=difficulty
	# || Example: ["minecraft:overworld=peaceful", "minecraft:the_end=hard"]
	dimensional_difficulty = []
	# || Used with dimensional_difficulty config option, when Dimensional Difficulties are enabled.
	# || Provides default difficulty for dimensions that aren't listed in dimensional_difficulty config option
	default_difficulty = "normal"
	# || List of dimensions where pvp is not allowed.
	# || Leave empty for to allow all dimensions.
	# || Format: modid:dimension
	# || Example: ["minecraft:overworld", "minecraft:the_end"]
	dimensional_pvp_blacklist = []
	# || List of item ids to blacklist from being mapped.
	# || Format: modid:item
	# || Example: minecraft:stone
	blacklist_item_ids = ["minecraft:bedrock", "minecraft:barrier"]
	# || List of entity ids to blacklist from being mapped.
	# || Format: modid:entityid
	# || Example Entry: minecraft:iron_golem
	# || Example List: ["minecraft:iron_golem", "minecraft:villager", "minecraft:wither", "minecraft:mooshroom"]
	blacklist_entity_ids = []
