["General Settings"]
	#Enable toggle wander behavior for cats (Default: true)
	enableBehaviorCats = true
	#Enable toggle wander behavior for wolves (Default: true)
	enableBehaviorWolves = true
	#Enable toggle wander behavior for parrots (Default: true)
	enableBehaviorParrots = true
	#Enhance cats' wander behavior, making them alternate between sitting, sleeping and wandering from time to time (Default: true)
	betterCatBehavior = true
	#Lower values makes cats sleep and sit more, higher values makes them wander more. Only applies if betterCatBehavior is enabled. (Default: 700)
	# Default: 700
	# Range: 200 ~ 2000
	catsRelaxingCooldown = 700
	#Enable mod behavior for possibly compatible modded entities (Default: true)
	enableModdedEntities = true
	#Whitelist of modded mob IDs allowed to use mod behavior. Copy IDs from the discovered list below into here. (Default: [friendsandfoes:glare, alexsmobs:capybara, minecraft:fox])
	moddedMobWhitelist = ["friendsandfoes:glare", "alexsmobs:capybara", "minecraft:fox"]
	#[READ-ONLY] Detected mobs that may or may not be compatible with mod behavior. Add these into the whitelist to turn on mod behavior. Requires loading a save to populate (Default: [])
	discoveredCompatibleMobs = ["alexsmobs:bald_eagle", "alexsmobs:caiman", "alexsmobs:capuchin_monkey", "alexsmobs:cosmaw", "alexsmobs:crocodile", "alexsmobs:crow", "alexsmobs:elephant", "alexsmobs:flutter", "alexsmobs:gorilla", "alexsmobs:grizzly_bear", "alexsmobs:kangaroo", "alexsmobs:komodo_dragon", "alexsmobs:mantis_shrimp", "alexsmobs:mimic_octopus", "alexsmobs:mudskipper", "alexsmobs:orca", "alexsmobs:raccoon", "alexsmobs:sugar_glider", "alexsmobs:tarantula_hawk", "alexsmobs:warped_toad", "iceandfire:amphithere", "iceandfire:cockatrice", "iceandfire:deathworm", "iceandfire:fire_dragon", "iceandfire:hippocampus", "iceandfire:hippogryph", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:pixie", "occultism:afrit", "occultism:demonic_husband", "occultism:demonic_wife", "occultism:djinni", "occultism:foliot", "occultism:marid", "occultism:otherworld_bird", "rpg_companions_tiny_dragons:tiny_dragon_01", "rpg_companions_tiny_dragons:tiny_dragon_02", "rpg_companions_tiny_dragons:tiny_dragon_03", "rpg_companions_tiny_dragons:tiny_dragon_04", "rpg_companions_tiny_dragons:tiny_dragon_05", "rpg_companions_tiny_dragons:tiny_dragon_06", "rpg_companions_tiny_dragons:tiny_dragon_07", "rpg_companions_tiny_dragons:tiny_dragon_08", "rpg_companions_tiny_dragons:tiny_dragon_09", "rpg_companions_tiny_dragons:tiny_dragon_10", "swem:wormieboi"]
	#Should log stuff (Default: false)
	debugMode = false
