import crafttweaker.api.fluid.IFluidStack;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.ItemDefinition;
import crafttweaker.api.resource.ResourceLocation;
import crafttweaker.api.tag.type.KnownTag;
import crafttweaker.api.text.MutableComponent;
import crafttweaker.api.text.Style;

public function colorWarn() as int { return 0xFF0000; }
public function colorInfo() as int { return 0x7F7F7F; }

public function toItem(tag as KnownTag<ItemDefinition>) as IItemStack {
    if !<tagmanager:item>.exists(tag) {
        throw new stdlib.Exception("\"" + tag.id.namespace + ":" + tag.id.path + "\" is an empty tag, it does not exist");
    }
    return tag.elements()[0].getDefaultInstance();
}

public function stripTags(resource as ResourceLocation) as void {
    for tag_manager in [<tagmanager:item>, <tagmanager:fluid>, <tagmanager:block>] {
        for tag in tag_manager.getTagsFor(resource) {
            tag_manager.removeId(tag, resource);
        }
    }
}

public function stripTagsAndHide(resource as IItemStack) as void {
    stripTags(resource.registryName);
    <tag:item:c:hidden_from_recipe_viewers>.addId(resource.registryName);
}

public function stripTagsAndConvert(oldItem as IItemStack, newItem as IItemStack) as void {
    stripTagsAndHide(oldItem);
    tooltipColor(oldItem, "This item is disabled", colorWarn());
    tooltip(oldItem, "If you somehow obtained this item, place it in a crafting grid to convert it into something useful");
    val recipeName = "autogenerated_convert_" + oldItem.registryName.namespace + oldItem.registryName.path + "_to_" + newItem.registryName.namespace + newItem.registryName.path;
    recipes.remove(oldItem); // Enable this when playing modpack time
    <recipetype:minecraft:crafting>.addShapeless(recipeName, newItem, [oldItem]);
}

public function stripTagsAndHideFluid(resource as IFluidStack) as void {
    stripTags(resource.registryName);
    <tag:fluid:c:hidden_from_recipe_viewers>.addId(resource.registryName);
}


public function tooltip(item as IItemStack, text as string) as void {
    tooltipColor(item, text, colorInfo());
}

public function tooltipColor(item as IItemStack, text as string, colorHex as int) as void {
    item.addTooltip(MutableComponent.literal(text).setStyle(Style.empty().withColor(colorHex)));
}

public function colors() as string[] {
    return ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"];
}